language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
   - stable

script:
  -   cargo build 
   -   cargo test
      
after_success:
    
